name: nyc_hackathon
version: '1.0.0'
config-version: 2

profile: nyc_hackathon

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_hackathon:
    +materialized: view
